version: '3.8'

services:
  mongodb:
    image: mongo:latest
    network_mode: bridge
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=AevatarDb

  redis:
    image: redis:latest
    network_mode: bridge
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  kafka:
    image: bitnami/kafka:latest
    network_mode: bridge
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka-data:/bitnami/kafka

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    network_mode: bridge
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  qdrant:
    image: qdrant/qdrant:latest
    network_mode: bridge
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-data:/qdrant/storage

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    network_mode: bridge
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4315:4315"  # OTLP gRPC
      - "9090:9090"  # Prometheus exporter

volumes:
  mongodb-data:
  redis-data:
  kafka-data:
  elasticsearch-data:
  qdrant-data: